name: gallery
description: Gallery App for uploading images.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^1.5.4
  retrofit: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700


