name: gallery
description: Gallery App for uploading images.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^1.5.4
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.0.3
  cached_network_image: ^3.2.2
  email_validator: ^2.1.16
  shimmer: ^2.0.0
  image_picker: ^0.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  injectable_generator: ^1.5.4
  freezed: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Changa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Changa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Changa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Changa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Changa-Light.ttf
          weight: 300
        - asset: assets/fonts/Changa-ExtraLight.ttf
          weight: 200


